name: PHPCS

on: [push, pull_request]

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
      - name: PHPStan
        uses: chindit/actions-phpstan@master
